### ISSUE TITLE
Apparently I get an error where the MTR modpack won't update for me

### ISSUE THREAD

**Issue by boiii3** [jonafanho/Minecraft-Mod-Updater#13]
**Crash Report**
![image](https://user-images.githubusercontent.com/70972774/206332479-cf12be28-c338-4a35-a20d-875f78690133.png)

**Comment by jonafanho** [comment]
This is because the resource pack server is down. It is unrelated to the Minecraft Mod Updater,

**Comment by boiii3** [comment]
Ok thanks for letting me know
